"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import styles from "../../styles/Subpages.module.css";
import homeStyles from "../../styles/Home.module.css";
import { Article } from "../../components/WritingPreview";
import ThemeToggle from "../../components/ThemeToggle";

const FALLBACK_10_ARTICLES: Article[] = [
  {
    title: "Optimizing TCP Socket Buffers in Rust for Edge Telemetry Pipelines",
    brief: "Deconstructing raw socket operations, system-level buffer tuning, and handling high-concurrency event loops using Rust's Tokio runtime.",
    url: "https://dlazyhntr.hashnode.dev/optimizing-tcp-sockets-in-rust",
    publishedAt: "2026-07-20T08:00:00Z"
  },
  {
    title: "Minimizing Layout Shifts: Building a Custom WebAssembly Render Engine",
    brief: "How we shifted UI layout calculations from the main browser thread into WebAssembly, achieving smooth 60fps renders under heavy data loads.",
    url: "https://dlazyhntr.hashnode.dev/wasm-layout-renderer",
    publishedAt: "2026-06-15T08:00:00Z"
  },
  {
    title: "Edge Cache vs. ISR: Architectural Trade-offs in Modern Frameworks",
    brief: "A detailed performance audit analyzing the LCP and TTFB metrics of edge-cached serverless functions compared to Incremental Static Regeneration.",
    url: "https://dlazyhntr.hashnode.dev/edge-vs-isr-audit",
    publishedAt: "2026-05-02T08:00:00Z"
  },
  {
    title: "Implementing Raft Consensus from Scratch in Go: Network Partitions",
    brief: "Lessons learned building a distributed key-value store, detailing state machines, log compaction, and leader election during severe network splits.",
    url: "https://dlazyhntr.hashnode.dev/raft-consensus-golang",
    publishedAt: "2026-04-12T08:00:00Z"
  },
  {
    title: "Securing AI Agents: Designing MicroVM Compiler Sandboxes",
    brief: "A guide to building secure, ephemeral execution sandboxes for running untrusted code generated by AI programming agents.",
    url: "https://dlazyhntr.hashnode.dev/secure-microvm-compiler",
    publishedAt: "2026-03-24T08:00:00Z"
  },
  {
    title: "Offloading UI Workloads: Advanced Thread-Scheduling with Web Workers",
    brief: "How to decouple network socket streaming from the DOM using worker contexts, offscreen canvas, and SharedArrayBuffers.",
    url: "https://dlazyhntr.hashnode.dev/advanced-web-workers",
    publishedAt: "2026-02-10T08:00:00Z"
  },
  {
    title: "Sub-Millisecond APIs: Cache Invalidations in Distributed Edge Nodes",
    brief: "Analyzing cache propagation latencies on globally distributed Cloudflare edge workers and designing active push invalidation models.",
    url: "https://dlazyhntr.hashnode.dev/sub-millisecond-edge-cache",
    publishedAt: "2026-01-05T08:00:00Z"
  },
  {
    title: "Visualizing Geospatial Clusters at Scale: Optimizing Mapbox GL",
    brief: "Implementing dynamic viewport spatial indexes and customized cluster filters to render 100k farming nodes smoothly in AgriLink.",
    url: "https://dlazyhntr.hashnode.dev/mapbox-cluster-rendering",
    publishedAt: "2025-11-20T08:00:00Z"
  },
  {
    title: "WebSockets Backpressure: Managing High-Frequency Streams in Node.js",
    brief: "How to prevent socket memory exhaustion and stream congestion using stream-drain events, buffer limits, and client flow control.",
    url: "https://dlazyhntr.hashnode.dev/websockets-backpressure-node",
    publishedAt: "2025-10-08T08:00:00Z"
  },
  {
    title: "Restoring Ancient Text: Sequence-to-Sequence Modeling on Epigraphic Corpora",
    brief: "Under the hood of Aeneas Model architectures: combining natural language transformers with historic context weights to restore eroded Latin slabs.",
    url: "https://dlazyhntr.hashnode.dev/aeneas-latin-epigraphy",
    publishedAt: "2025-09-02T08:00:00Z"
  }
];

export default function WritingArchive() {
  const [articles, setArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    async function fetchWritingArchive() {
      const query = `
        query {
          publication(host: "dlazyhntr.hashnode.dev") {
            posts(first: 10) {
              edges {
                node {
                  title
                  brief
                  url
                  publishedAt
                }
              }
            }
          }
        }
      `;

      try {
        const res = await fetch("https://gql.hashnode.com", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ query }),
        });

        if (!res.ok) {
          throw new Error("GQL query request failed");
        }

        const json = await res.json();
        const edges = json?.data?.publication?.posts?.edges;

        if (edges && Array.isArray(edges) && edges.length > 0) {
          const formatted: Article[] = edges.map((e: any) => ({
            title: e.node.title,
            brief: e.node.brief || "Click to read full article.",
            url: e.node.url,
            publishedAt: e.node.publishedAt
          }));
          setArticles(formatted);
        } else {
          setArticles(FALLBACK_10_ARTICLES);
        }
      } catch (err) {
        console.warn("Failed to fetch Hashnode post ledger, using fallback:", err);
        setArticles(FALLBACK_10_ARTICLES);
      } finally {
        setLoading(false);
      }
    }

    fetchWritingArchive();
  }, []);

  return (
    <div className={homeStyles.pageContainer}>
      {/* Background glow elements */}
      <div className={homeStyles.bgGlow}>
        <div className={homeStyles.glowCyan} style={{ top: "8%" }} />
        <div className={homeStyles.glowViolet} style={{ top: "55%" }} />
      </div>

      <header className={homeStyles.header}>
        <div className={homeStyles.headerInner}>
          <Link href="/" className={homeStyles.logo}>
            <span className={homeStyles.logoIcon}>◬</span> IamAdedo
          </Link>
          <nav className={homeStyles.nav}>
            <Link href="/" className={homeStyles.navLink}>
              Matrix
            </Link>
            <Link href="/projects" className={homeStyles.navLink}>
              Projects
            </Link>
            <Link href="/archive" className={homeStyles.navLink}>
              Archive
            </Link>
            <Link href="/writing" className={homeStyles.navLink} style={{ color: "var(--accent-cyan)" }}>
              Writing
            </Link>
            <ThemeToggle />
          </nav>
        </div>
      </header>

      <main className={homeStyles.mainContent}>
        {/* Header Block */}
        <section className={styles.subpageHeader}>
          <Link href="/" className={styles.backLink} id="back-to-matrix-from-writing">
            [ ← Return to Matrix ]
          </Link>
          <h1 className={styles.title}>Publications & Engineering Logs</h1>
          <p className={styles.subtitle}>
            A deep-dive archive mapping systems architecture designs, performance analyses, and telemetry audits.
          </p>
        </section>

        {/* Dynamic Articles List */}
        <section className={styles.sectionSpacer} style={{ borderBottom: "none" }}>
          {loading ? (
            <div style={{ textAlign: "center", padding: "80px 0", color: "var(--text-secondary)" }}>
              ⚙ Connecting to publication streams...
            </div>
          ) : (
            <div className={styles.articleList} id="extended-writing-ledger">
              {articles.map((article, idx) => (
                <a
                  key={idx}
                  href={article.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className={styles.listCard}
                  id={`archive-article-${idx}`}
                >
                  <div className={styles.listHeader}>
                    <span>LOG ENTRY #{String(idx + 1).padStart(2, "0")}</span>
                    <span>
                      {new Date(article.publishedAt).toLocaleDateString(undefined, {
                        year: "numeric",
                        month: "long",
                        day: "numeric",
                      })}
                    </span>
                  </div>
                  <h3 className={styles.listTitle}>{article.title}</h3>
                  <p className={styles.listExcerpt}>{article.brief}</p>
                  <div className={styles.listFooter}>
                    Access System Publication Log <span>→</span>
                  </div>
                </a>
              ))}
            </div>
          )}

          {/* Action button redirecting to publication domain root */}
          {!loading && (
            <div className={styles.actionButtonWrapper}>
              <a
                href="https://dlazyhntr.hashnode.dev"
                target="_blank"
                rel="noopener noreferrer"
                className={homeStyles.btnPrimary}
                id="visit-hashnode-root-btn"
              >
                Visit Hashnode Publication Root ↗
              </a>
            </div>
          )}
        </section>
      </main>

      <footer className={homeStyles.footer}>
        <div className={homeStyles.footerInner}>
          <div>
            <Link href="/" className={homeStyles.footerLogo}>
              IamAdedo // distributed systems
            </Link>
          </div>
          <div>© {new Date().getFullYear()} IamAdedo. All Rights Reserved.</div>
        </div>
      </footer>
    </div>
  );
}
